module.exports = {
    auth        : require(__sevdir + '/auth/controller'),
    captions    : require(__sevdir + '/captions/controller'),
    clients     : require(__sevdir + '/clients/controller'),
    edits       : require(__sevdir + '/edits/controller'),
    emails      : require(__sevdir + '/emails/controller'),
    games       : require(__sevdir + '/games/controller'),
    globals     : require(__sevdir + '/globals/controller'),
    ideas       : require(__sevdir + '/ideas/controller'),
    jobs        : require(__sevdir + '/jobs/controller'),
    masters     : require(__sevdir + '/masters/controller'),
    projects    : require(__sevdir + '/projects/controller'),
    scenes      : require(__sevdir + '/scenes/controller'),
    scripts     : require(__sevdir + '/scripts/controller'),
    shotlists   : require(__sevdir + '/shotlists/controller'),
    sources     : require(__sevdir + '/sources/controller'),
    team_invites: require(__sevdir + '/team_invites/controller'),
    teams       : require(__sevdir + '/teams/controller'),
    users       : require(__sevdir + '/users/controller'),
    validations : require(__sevdir + '/validations/controller'),
    voiceovers  : require(__sevdir + '/voiceovers/controller')
}
